# Generated by Django 4.1.2 on 2022-11-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarks', related_query_name='bookmark', to='feed.post'),
        ),
    ]
