# Generated by Django 4.1.2 on 2022-11-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_user_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', related_query_name='bookmark', to='feed.post'),
        ),
    ]
