# Generated by Django 4.1.2 on 2022-11-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_view_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(to='feed.view'),
        ),
    ]
