# Generated by Django 4.1.2 on 2022-11-05 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_post_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='update_date',
            new_name='create_date',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likes', related_query_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
