# Generated by Django 4.1.2 on 2022-11-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_rename_update_date_view_create_date_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
