# Generated by Django 4.1.3 on 2023-02-18 16:22

import django.core.validators
from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(max_length=128, null=True)),
                ('thumbnail', models.ImageField(help_text='This image will be displayed on article listing. The recommended size 1920x1440 and recommended ratio is 4:3.', upload_to='photos/%Y/%m/%d/', verbose_name='Article listing cover image')),
                ('body', django_editorjs_fields.fields.EditorJsJSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'title', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name', 'pk'],
            },
        ),
    ]
