# Generated by Django 4.1.3 on 2023-02-12 20:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('slug', models.SlugField(max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'categories',
                'verbose_name_plural': 'categories',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, validators=[django.core.validators.MinLengthValidator(3, 'The title must contain at least 3 characters.')])),
                ('slug', models.SlugField(max_length=128, null=True)),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('body', django_editorjs_fields.fields.EditorJsJSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='articles.category')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-created_at', 'title', 'slug', 'pk'],
            },
        ),
    ]
