# Generated by Django 4.1.3 on 2023-02-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow_once',
        ),
    ]
