# Generated by Django 4.1.3 on 2023-02-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_follow_options_follow_created_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='prevent_self_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('follower', models.F('author')), _negated=True), name='prevent_self_follow', violation_error_message='The author cannot follow himself.'),
        ),
    ]
