# Generated by Django 4.1.3 on 2023-02-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_thumbnail_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_at', 'title', 'pk')},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name', 'pk'), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
