# Generated by Django 4.1.3 on 2023-02-28 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='target_content_type',
            new_name='action_object_content_type',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='target_object_id',
            new_name='action_object_object_id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='sender',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='content',
            new_name='verb',
        ),
    ]
