# Generated by Django 4.1.3 on 2023-02-28 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0002_rename_target_content_type_notification_action_object_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='target_content_type', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='target_object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
