# Generated by Django 4.1.3 on 2023-02-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_follow_follow_once'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='not_follow_self',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'author'), name='unique_followers'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('author', models.F('follower'))), name='prevent_self_follow'),
        ),
    ]
