# Generated by Django 4.1.3 on 2023-02-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_follow_notifications_user_new_article_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='new_article_notifications',
            field=models.BooleanField(default=True, help_text='Get notified about new articles by authors you follow.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='new_follow_notifications',
            field=models.BooleanField(default=True, help_text='Recive notifications of your new followers.'),
        ),
    ]
