# Generated by Django 4.1.3 on 2023-01-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, height_field=64, null=True, upload_to='photos/%Y/%m/%d/', width_field=64),
        ),
    ]
