# Generated by Django 4.1.3 on 2023-02-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_follow_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follow_notifications',
            new_name='new_article_notifications',
        ),
        migrations.AddField(
            model_name='user',
            name='new_follow_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
